name: Codemap and line-limit checks

on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  codemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verify line limits (<=300 lines for .py,.js)
        run: python scripts/verify_limits.py

      - name: Generate codemap (JSON + Markdown)
        run: python scripts/generate_codemap.py

      - name: Commit codemap if changed
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          if [[ -n "$(git status --porcelain codemap.json CODEMAP.md)" ]]; then
            git add codemap.json CODEMAP.md
            git commit -m "chore: update codemap [skip ci]"
            git push origin "HEAD:${{ github.ref_name }}"
          else
            echo "No codemap changes"
          fi
